### ISSUE TITLE
你好，请问一下可以提供一下您的处理后的SECOND的数据集吗

### ISSUE THREAD

**Issue by Dap1Aa** [byyztgxz/Decoder_Fusion#1]

**Comment by byyztgxz** [comment]
你指的是怎么处理？数据集划分还是从读取样本图像到输入神经网络之间的处理？

**Comment by Dap1Aa** [comment]
都要可以吗？我处理好数据集准备开始训练但是遇到了问题RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of size: : [8, 512, 512, 3]

**Comment by byyztgxz** [comment]
我这个项目里有个dataset_split文件夹，里面是划分的训练集和测试集的namelist。至于处理数据集的方式，我是读取之后进行了标准化，你可以直接参考项目里dataset_process里面的SECOND_process。如果你也想只进行归一化的话可以直接用这个代码，改个路径就好了。我这里没有处理好的数据因为我都是在训练过程中处理的。

**Comment by Dap1Aa** [comment]
好的，我去试试，麻烦了！

**Comment by byyztgxz** [comment]
没什么麻烦的，加油

**Comment by Dap1Aa** [comment]
我怀疑是我环境的问题，请问您能否提供一下您python环境的python版本和torch的版本

**Comment by Dap1Aa** [comment]
你好，我想问一下您环境的torch版本，因为我发现我运行报错都是在torch下面，所以想问一下您的cuda版本和对应的torch版本。
![6211b77a-8d0b-4c79-a6f5-8085c4943732](https://github.com/user-attachments/assets/6328bb9f-f63a-4151-bdaf-f52dc4beb0d1)

**Comment by byyztgxz** [comment]
项目已添加requirements.txt文件，其中完全覆盖本项目运行所需要的库及其版本，以供参考。

**Comment by Dap1Aa** [comment]
太感谢了，辛苦您答疑！

**Comment by Dap1Aa** [comment]
您好，现在结果已经跑出来了。但是我没有找到根据结果模型进行验证的代码，请问是哪部分呢？就是根据最优模型进行推断语义变化检测图的代码。

**Comment by Dap1Aa** [comment]
您好，请问推理代码可以提供一下吗？

**Comment by byyztgxz** [comment]
你好，本项目已上传用于可视化模型预测结果的代码部分。由于不同的模型输出不同、分支不同，本部分代码仅适用于如本文两个SS分支和一个CD分支的三分支SCD架构。

**Comment by Dap1Aa** [comment]
非常感谢！望您以后顺利！

**Comment by byyztgxz** [comment]
谢谢，你也是

**Comment by hyl-go** [comment]
为什么我在使用requirements.txt安装时报了好多错误，并且在代码里面也存在一些方法或者变量使用了但是却未定义的情况。有没有就是完整的可以正常使用的版本呐，感谢。
