### ISSUE TITLE
Landsat-SCD数据集的训练集和测试集是怎么分的？

### ISSUE THREAD

**Issue by tianyi1565** [byyztgxz/Decoder_Fusion#2]
你好，请问Landsat-SCD数据集的训练集和测试集是怎么分的？

**Comment by byyztgxz** [comment]
你好，关于Landsat-SCD数据集训练集和测试集的划分方式：首先将数据集样本名称按照原名称顺序从1开始重命名。然后划分的namelist见附件。
[Landsat-SCD_train_set(recode).txt](https://github.com/user-attachments/files/18272014/Landsat-SCD_train_set.recode.txt)
[Landsat-SCD_val_set(recode).txt](https://github.com/user-attachments/files/18272015/Landsat-SCD_val_set.recode.txt)

**Comment by tianyi1565** [comment]
好的，感谢你的回复

**Comment by CCSSF** [comment]
> 你好，关于Landsat-SCD数据集训练集和测试集的划分方式：首先将数据集样本名称按照原名称顺序从1开始重命名。然后划分的namelist见附件。 [Landsat-SCD_train_set（重新编码）.txt](https://github.com/user-attachments/files/18272014/Landsat-SCD_train_set.recode.txt) [Landsat-SCD_val_set（recode）.txt](https://github.com/user-attachments/files/18272015/Landsat-SCD_val_set.recode.txt)

您好，请问可以提供一下您划分完成后的Landsat-SCD数据集吗？我下载的Landsat-SCD数据集总共只有2300多张，看您给的划分namelist超过了两千张图片

**Comment by byyztgxz** [comment]
> > 你好，关于Landsat-SCD数据集训练集和测试集的划分方式：首先将数据集样本名称按照原名称顺序从1开始重命名。然后划分的namelist见附件。 [Landsat-SCD_train_set（重新编码）.txt](https://github.com/user-attachments/files/18272014/Landsat-SCD_train_set.recode.txt) [Landsat-SCD_val_set（recode）.txt](https://github.com/user-attachments/files/18272015/Landsat-SCD_val_set.recode.txt)
> 
> 您好，请问可以提供一下您划分完成后的Landsat-SCD数据集吗？我下载的Landsat-SCD数据集总共只有2300多张，看您给的划分namelist超过了两千张图片

您好，在论文《 A transformer-based Siamese network and an open optical dataset for semantic change detection of remote sensing [images》中，作者详细介绍了Landsat-SCD数据集，并提供了数据集下载地址。
![Landsat-SCD](https://github.com/user-attachments/assets/06ee48f7-3655-40d0-9e0d-af2c64a40c05)
并且，论文中介绍，Landsat-SCD数据集包含图像对数量超过两千。
![Uploading L.png…]()

**Comment by CCSSF** [comment]
感谢您的回复，谢谢！

**Comment by tianyi1565** [comment]
你好，请问Landsat-SCD数据集在训练和测试时是怎么处理的，labelA和labelB是怎么划分的？
